name: Build

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Switch Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: build-${{ hashFiles('**/package-lock.json') }}

    - name: Install deps
      run: npm ci

    - name: Build
      run: npm run build