export enum IItemSlot {
    HEAD = "HEAD",
    NECK = "NECK",
    SHOULDER = "SHOULDER",
    CHEST = "CHEST",
    WAIST = "WAIST",
    LEGS = "LEGS",
    FEET = "FEET",
    WRIST = "WRIST",
    HANDS = "HANDS",
    FINGER_1 = "FINGER_1",
    FINGER_2 = "FINGER_2",
    TRINKET_1 = "TRINKET_1",
    TRINKET_2 = "TRINKET_2",
    BACK = "BACK",
    MAIN_HAND = "MAIN_HAND",
    OFF_HAND = "OFF_HAND",
}