name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    environment: cache

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run cache
        env:
          SEASON: season-sl-1
          CACHE_TO: 1
          BNET_ID: ${{ secrets.BNET_ID }}
          BNET_SECRET: ${{ secrets.BNET_SECRET }}
